apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: test
spec:
  rules:
  - host: test-argocd.server-in.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-1
            port:
              number: 80
