apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic
spec:
  rules:
  - host: test-argocd.server-in.com
    http:
      paths:
      - backend:
          service:
            name: s1
            port:
              number: 80
