apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
spec:
  selector:
    matchLabels:
      app: kube
  replicas: 6 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: abudevops194/final-web
        ports:
        - containerPort: 8080
